### ISSUE TITLE
Misleading README

### ISSUE THREAD

**Issue by SvenSapphire** [farkon00/mol-mass-solver#1]
Hey, your README is hard to read... could you please use a little bit of format and styling please?
Greetings

**Comment by Ellipse0934** [comment]
Feel free to file a PR
:)

**Comment by farkon00** [comment]
How about this formatting
# mOlEcUlAr mAsS SoLvEr
eXaMpLe:
```
$ GiT ClOnE HtTpS://GiThUb.cOm/fArKoN00/MoL-MaSs-sOlVeR
$ Cd mO
```
l-mAsS-SoLvEr
$ pYtHoN3 `mAi`N.Py # uSe cTrL + C To eXiT
H2O
18
cA*(Oh)2*  
97
^c
$ p**YtHoN3 mA**iN.Py -V # VeRbOsE
Co2
1 * 12 + 2 * 16 = 44
^C
$ RlWrAp pYtHoN3 mAiN.Py # tO AdD HiStOrY AnD NaViGaTiOn wItH ArRoWs, RlWrAp iS An eXtErNaL PaCkAgE

**Comment by SvenSapphire** [comment]
That is just perfect 😍
